#pragma once

#include "../common.h"
#include "World.h"

#include <cstdint>
#include <string>

namespace specific
{
    struct Control
    {
        uint8_t m_speed;
        uint8_t m_cached_speed;
        uint8_t m_angle;
        uint8_t m_cached_angle;
        uint8_t m_eject_ct;
        uint8_t m_split_ct;
        uint8_t m_drop_ct;
    };

    struct BlobData
    {
        BlobData(const std::string name, const std::string ticket) : m_name(name), m_ticket(ticket) {}

        const std::string m_name;
        const std::string m_ticket;
        not_implemented_t m_skin = nullptr;
        not_implemented_t m_rainbow_cycle = nullptr;
        not_implemented_t m_name_font = nullptr;
        not_implemented_t m_halo = nullptr;
        not_implemented_t m_hat = nullptr;
        not_implemented_t m_particle = nullptr;
        not_implemented_t m_visibility = nullptr;
        not_implemented_t m_eject_skin = nullptr;
    };

    struct Net
    {
        Net(const std::string ip, const uint16_t port) : m_ip(ip), m_port(port) {}

        not_implemented_t m_connection_state = nullptr;
        const std::string m_ip;
        const uint16_t m_port;
        const not_implemented_t m_sock = nullptr;
        static models::World *p_world; // static to share with other bots

        /*
            Two tokens received from CONNECT_RESULT_2 (0x01).
            Used to identify the client server-side.
        */

        uint32_t cr2_token1;
        uint32_t cr2_token2;

        /*
            Same as above, but randomly generated by ourselves.
            These also need to be provided sometimes when
            sending packets, e.g. DISCONNECT (0x07).
        */

        uint32_t rng_token1;
        uint32_t rng_token2;
    };
}

namespace models
{
    class Bot
    {
    public:
        Bot(const uint8_t uniquifier, const std::string name, const std::string ticket, const std::string ip, const uint16_t port);

        const uint8_t m_uniquifier;
        specific::Control *p_control;
        specific::BlobData *p_blob_data;
        specific::Net *p_net;
    };
}
